### ISSUE TITLE
Create View Progress Report Site

### ISSUE THREAD

**Issue by R-Ramana** [Orbital-Knewbie/Knewbie#12]
Static Site to display personalized progress reports for individual students. Need to come up with a scoring matrix.

**Comment by hughjazzman** [comment]
To do for this issue, with reference to #73:

- convert datetime to use in JSON for overall proficiency
- get topical data as a list of 2 lists with first being topics, 2nd being proficiency level

**Comment by R-Ramana** [comment]
> To do for this issue, with reference to #73:
> 
> * convert datetime to use in JSON for overall proficiency
> * get topical data as a list of 2 lists with first being topics, 2nd being proficiency level

Will update this issue to be completed by Milestone 3 instead.
