### ISSUE TITLE
Update features to reflect REST API

### ISSUE THREAD

**Issue by hughjazzman** [Orbital-Knewbie/Knewbie#46]
PR #45 #40 #39
Issues #8 #7 #10 #13 #18 #20 #21 #22 #23 #24 #25 #26 #27 #28 #30
Change the following to reflect REST API. Apply REST API when working on the rest.

- Password reset to a PUT request on user/password
- Register account to POST request on user
- Delete account to DELETE request on user
- Update knewbie ID to PUT request on user/knewbieid

**Comment by R-Ramana** [comment]
I'll update this to be completed by Milestone 3 instead

**Comment by hughjazzman** [comment]
Fairly important todo here:

- Change class code to a POST request on a FlaskForm
- Update Knewbie ID to a POST request on a FlaskForm

Currently, these are GET requests which should be idempotent.

**Comment by hughjazzman** [comment]
[The tutorial here will be useful.](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xxiii-application-programming-interfaces-apis)
