### ISSUE TITLE
'Go Back Home' button when handling errors

### ISSUE THREAD

**Issue by R-Ramana** [Orbital-Knewbie/Knewbie#48]
Simple button and routing to go back to the dashboard/home.

**Comment by hughjazzman** [comment]
I think this is not necessary. Just a back to home/dashboard button is fine.

**Comment by R-Ramana** [comment]
> I think this is not necessary. Just a back to home/dashboard button is fine.

We do have quite a fair bit of redirection, not very user friendly if they get an error from say their class page, and then the only option they have is back to home/dashboard. Okay if not logged in, cause literally they can only do one thing from the homepage but otherwise might have more clicks if we don't route back to their last accessed page?

**Comment by hughjazzman** [comment]
Disagree. There is a back button.

**Comment by R-Ramana** [comment]
Fair enough
