### ISSUE TITLE
Create Github Wiki

### ISSUE THREAD

**Issue by R-Ramana** [Orbital-Knewbie/Knewbie#52]
Move documentations to github wiki.

**Comment by R-Ramana** [comment]
Can close the issue already. Help me verify at the wiki. Some images not showing as not yet uploaded into the folder + need to make the user guides less verbose, but we can directly make the changes in the wiki from now.

**Comment by hughjazzman** [comment]
I fixed the links on the main page, but all the links within the documents will need to be fixed as well.

You can just use the HTML tag `<img>` to resize the images.
https://stackoverflow.com/questions/24383700/resize-image-in-the-wiki-of-github-using-markdown
